project:
  type: website
  output-dir: docs

website:
  bread-crumbs: false
  page-navigation: true
  title: "Inferência I"
  sidebar:
    style: "docked"
    search: false
    border: false
    logo: img/inferencia1-logo-sem-borda.png
    contents:
    - section: "Informações da disciplina"
      contents: 
      - href: info/dados_gerais.qmd
        text: "Dados gerais"
      - href: info/ementa.qmd
        text: "Ementa e objetivos"
      - href: info/conteudo.qmd
        text: "Conteúdo"
      - href: info/bibliografia.qmd
        text: "Bibliografia"
      - href: info/cronograma.qmd
        text: "Cronograma"
    
    - section: "Aulas"
      contents: 
      - section: "Parte 1: Princípios da Estimação Pontual"
        contents:
          - href: aulas/1-Apresentacao_da_disciplina.qmd
            text: "1- Apresentação da Disciplina e Conceitos Iniciais"
      
      - section: "Parte 2: Métodos de Estimação"
        contents:
          - href: aulas/1-Apresentacao_da_disciplina.qmd
            text: "1- Apresentação da Disciplina e Conceitos Iniciais"
      
      - section: "Parte 3: Estimação por intervalo"
        contents:
          - href: aulas/1-Apresentacao_da_disciplina.qmd
            text: "1- Apresentação da Disciplina e Conceitos Iniciais"
    
    - href: PDFs/listas/listas_de_exercicio.qmd
      text: "Listas de Exercício"
    - href: PDFs/tabelas/tabelas.qmd
      text: "Tabelas"



format:
  html:
    theme: styles.scss
    toc: true
    grid:
      sidebar-width: 300px
resources:
  - PDFs/**