---
title: "Critério da Fatoração de Neyman"
subtitle: "ESTAT0078 -- Inferência I"
author:
  name: | # indica que o campo name terá múltiplas linhas
    Prof. Dr. Sadraque E. F. Lucena<br>
    <span style="font-size:.8em;">sadraquelucena@academico.ufs.br</span>
    <br>
    <a href="http://sadraquelucena.github.io/inferencia1" style="font-size:.8em;">http://sadraquelucena.github.io/inferencia1</a>
  
format:
  revealjs:
    theme: meutema.scss
    width: 1024
    height: 768
    margin: 0.1         # margem em torno do conteúdo
    min-scale: 0.2       # escala mínima permitida
    max-scale: 2.0       # escala máxima permitida
    slide-number: true
    code-line-numbers: false # sem numero das linhas nos code chunks
    subtitle-style: "font-size: 2em; font-weight: bold;"  # Aqui é onde aumentamos o subtítulo
    logo: imagens/ufs_horizontal_positiva.png
    transition: fade
    transition-speed: fast
    scss: meutema.scss

lang: pt-BR

---

## Teorema 7.1: Critério da Fatoração de Neyman

Sejam $X_1, \ldots, X_n$ uma amostra aleatória da distribuição da variável aleatória $X$ com função de densidade (ou de probabilidade) $f(x)$ e função de verossimilhança $L(\theta; \underset{\widetilde{\phantom{a}}}{x})$. Temos, então, que a estatística $T = T(X_1, \ldots, X_n)$ é suficiente para $\theta$, se e somente se pudermos escrever
			
$$
  L(\theta; \underset{\widetilde{\phantom{a}}}{x}) = h(x_1,\ldots,x_n) g_\theta(T(x_1,\ldots,x_n)),
$$

:::: {.columns}

::: {.column width=15%}
em que
:::

::: {.column width=85%}

-   $h(x_1,\ldots,x_n)$ só envolve $x_1,\ldots,x_n$ (não envolve $\theta$);
-   $g_\theta(T(x_1,\ldots,x_n))$ envolve $\theta$ e $T(x_1,\ldots,x_n)$.
				
-   **Prova:** Livro do Bolfarine, pág. 22.
:::

::::


## Exemplo 7.1

Seja $X_1, \ldots, X_n$ uma amostra aleatória da distribuição de Poisson com parâmetro $\theta$. Use o critério da fatoração para mostrar que $T(\underset{\widetilde{\phantom{a}}}{x})=\sum\limits_{i=1}^n X_i$ é suficiente para $\theta$.

<br>

::: {.callout-note title="Lembrete"}

$X\sim$ Poisson($\theta$): $f(x)=\frac{e^{-\theta}\theta^x}{x!}$, $x=0,1,2,\ldots$
:::




## Exemplo 7.2
Seja $X_1, \ldots, X_n$ uma amostra aleatória da variável $X\sim U(0,\theta)$. Encontre uma estatística suficiente para $\theta$ usando o critério da fatoração.

<br>

::: {.callout-note title="Lembrete"}

$X\sim U(a,b)$:
$$
  f(x)=\frac{1}{b-a} I_{(a,b)}(x) \quad \text{em que} \quad I_{(a,b)}(x) = \begin{cases}
				1, & a<x<b,\\
				0, & \text{caso contrário}.
				\end{cases}
$$

:::




## Exemplo 7.3

Seja $X_1, \ldots, X_n$ uma amostra aleatória da distribuição $N(\mu,1)$. Encontre uma estatística suficiente para $\mu$ usando o critério da fatoração.

<br>

::: {.callout-note title="Lembrete"}

$X\sim N(\mu,\sigma^2)$: $f(x)=\frac{1}{\sigma\sqrt{2\pi}} e^{-\frac{(x-\mu)^2}{2\sigma^2}} ,~ -\infty<x<\infty$

:::




## Exemplo 7.4

Seja $X_1, \ldots, X_n$ uma amostra aleatória da distribuição Bernoulli$(\theta)$. Encontre uma estatística suficiente para $\theta$ usando o critério da fatoração.

<br>

::: {.callout-note title="Lembrete"}

$X\sim \text{Bernoulli}(\theta)$: $f(x)=\theta^x (1-\theta)^{1-x}, ~ x = 0,1$

:::




# Fim