---
title: "Cronograma de Aulas"
format:
  html:
    toc: false
    anchor-sections: false
---

Confira abaixo o cronograma de aulas do semestre, baseado no [calendário acadêmico do período 2025-2](/PDFs/calendario_academico-2025-1-2.pdf){target="_blank"}.


| Aula   | Data                        | Assunto Previsto                 |
|:------:|:----------------------------|:---------------------------------|
| 1      | Terça, 13 de maio de 2025   | Recepção dos alunos              |
| 2      | Quinta, 15 de maio de 2025  | Recepção dos alunos              |
| 3      | Terça, 20 de maio de 2025   | Apresentação da disciplina       |
| 4      | Quinta, 22 de maio de 2025  | Introdução ao RStudio + GitHub   |
| 5      | Terça, 27 de maio de 2025   | Introdução ao LaTeX              |
| 6      | Quinta, 29 de maio de 2025  | Estrutura básico do LaTeX        |
| 7      | Terça, 03 de junho de 2025  | Ambiente matemático no LaTeX     |
| 8      | Quinta, 05 de junho de 2025 | Tabelas no LaTeX                 |
| 9      | Terça, 10 de junho de 2025  | Figuras no LaTeX                 |
| 10     | Quinta, 12 de junho de 2025 | Bibliografia no LaTeX            |
| 11     | Quinta, 17 de junho de 2025 | Avaliação 1                      |
| 12     | Terça, 01 de julho de 2025  | Quarto                           |
| 13     | Quinta, 03 de julho de 2025 | Geração de Números aleatórios    |
| 14     | Quinta, 10 de julho de 2025 | Geração de Variáveis Aleatórias Discretas    |
| 15     | Terça, 15 de julho de 2025 | Geração de Variáveis Aleatórias Contínuas    |
| 16     | Terça, 17 de julho de 2025 | Geração de Variáveis Aleatórias Contínuas    |
| 17     | Terça, 22 de julho de 2025 | Geração de Variáveis Aleatórias Contínuas    |
| 18     | Terça, 24 de julho de 2025 | Geração de um processo de Poisson Homogêneo    |
| 19     | Terça, 29 de julho de 2025 | Geração de um processo de Poisson Não Homogêneo    |
| 20     | Terça, 31 de julho de 2025 | Avaliação 2    |
| 21     | Terça, 05 de agosto de 2025 | O Método de Integração de Monte Carlo    |
| 22     | Terça, 12 de agosto de 2025 | O Método de Monte Carlo para Estimação    |
| 23     | Terça, 14 de agosto de 2025 | Método de Reamostragem Bootstrap    |
| 24     | Terça, 19 de agosto de 2025 | Aplicações do Método Bootstrap    |

